name: Build and push to docker hub

on:
  workflow_dispatch:
    inputs:
      target:
        type: string
        required: true
        description: Target version of acme-dns to use

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and puush
        env:
          IMG_VERSION: ${{ inputs.target }}
        run: ./docker-buildx.sh $IMG_VERSION
